export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_WORKER_LOADING = 'GET_WORKER_LOADING';
export const GET_WORKER_SUCCESS = 'GET_WORKER_SUCCESS';
export const GET_WORKER_FAIL = 'GET_WORKER_FAIL';


export const EDIT_WORKER_LOADING = 'EDIT_WORKER_LOADING';
export const EDIT_WORKER_SUCCESS = 'EDIT_WORKER_SUCCESS';
export const EDIT_WORKER_FAIL = 'EDIT_WORKER_FAIL';
